### ISSUE TITLE
Counting devices not possible

### ISSUE THREAD

**Issue by basz** [balena-io/balena-sdk#1422]
## Expected Behavior

I would expect to be able to count devices

## Actual Behavior

Error: Unknown pine option: $count

## Steps to Reproduce the Problem

```
    const countResult = await this.sdk.models.device.getAllByApplication(this.config.fleetSlug, {
        $count: {},
      });
```

This might be related to https://github.com/balena-io/balena-sdk/pull/1293

## Specifications

- SDK version: 19.6.1
- Browser: not applicable
- Node version: v20.13.1
- Npm version: 10.5.2
- OS: MacOS

I guess we are trying to create this request eventually as that works. It could also be that counting should be done entirely different. Please enlighten me :-)

```
curl -X GET 'https://api.balena-cloud.com/v6/device/$count?$filter=belongs_to__application%20eq%20APP_ID' \
-H "Content-Type: application/json" \
-H "Authorization: Bearer XXXXX"
```

**Comment by basz** [comment]
```
Error: Unknown pine option: $count
     at mergePineOptions (.../node_modules/.pnpm/balena-sdk@19.6.1/node_modules/balena-sdk/es2015/util/index.js:88:15)
     at Object.<anonymous> (.../node_modules/.pnpm/balena-sdk@19.6.1/node_modules/balena-sdk/es2015/models/device.js:311:65)
     at Generator.next (<anonymous>)
     at fulfilled (.../node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:166:62)
     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
