### ISSUE TITLE
Using balena.logs.subscribe(<balena device uuid>) on node.js produces xmlhttprqeuest error

### ISSUE THREAD

**Issue by jacobkring** [balena-io/balena-sdk#637]
When trying to get the logs via subscription/EventEmitter as shown in the docs using Node.js and on an ubuntu machine.

Like this:
```
balena.logs.subscribe(<my device uuid>).then(function(logs) {
	logs.on('line', function(line) {
		console.log(line);
	});
});
```

I'm getting the following error with some traceback..
```
Unhandled rejection ReferenceError: XMLHttpRequest is not defined
    at xhrTransport (/mypathhere//node_modules/fetch-readablestream/lib/xhr.js:30:15)
    at fetchStream (/mypathhere//node_modules/fetch-readablestream/lib/index.js:22:10)
    at requestAsync (/mypathhere//node_modules/balena-request/build/utils.js:333:7)
    at /mypathhere//node_modules/balena-request/build/utils.js:402:12
    at /mypathhere//node_modules/balena-request/build/progress.js:112:12
    at tryCatcher (/mypathhere//node_modules/balena-request/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/mypathhere//node_modules/balena-request/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/mypathhere//node_modules/balena-request/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/mypathhere//node_modules/balena-request/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/mypathhere//node_modules/balena-request/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/mypathhere//node_modules/balena-request/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/mypathhere//node_modules/balena-request/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/mypathhere//node_modules/balena-request/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/mypathhere//node_modules/balena-request/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```

Let me know if I can help/provide more information..

**Comment by jacobkring** [comment]
Not sure how it happened but the isBrowser flag needed to be set explicitly to false on my node instance.. everything seemed to work just fine after that.

**Comment by thgreasi** [comment]
Hi,
Thanks for sharing back your findings.
Could you please provide some extra details about your setup?
It's weird that you had to manually set the `isBrowser` option.
Is there any change that a `window` variable is available on the global scope of your environment?
