### ISSUE TITLE
Host OS update fails immediately (before initiating) with 500 Internal Server Error (BalenaRequestError)

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-sdk#750]
User reported, and I confirmed as a support agent, that a host OS update fails immediately (before initiating) via either the web dashboard of the balena CLI:

```
$ DEBUG=1 balena device os-update <uuid> --version 2.38.3+rev3.prod
[debug] original argv0="node" argv=[/Users/paulo/.nvm/versions/node/v10.16.3/bin/node,/Users/paulo/.nvm/versions/node/v10.16.3/bin/balena,device,os-update,9000622,--version,2.38.3+rev3.prod] length=7
? Host OS updates require a device restart when they complete. Are you sure you want to proceed? Yes
BalenaRequestError: Request error: [object Object]
    at /Users/paulo/.nvm/versions/node/v10.16.3/lib/node_modules/balena-cli/node_modules/balena-request/build/request.js:197:17
    at tryCatcher (/Users/paulo/.nvm/versions/node/v10.16.3/lib/node_modules/balena-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/paulo/.nvm/versions/node/v10.16.3/lib/node_modules/balena-cli/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/paulo/.nvm/versions/node/v10.16.3/lib/node_modules/balena-cli/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/paulo/.nvm/versions/node/v10.16.3/lib/node_modules/balena-cli/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/paulo/.nvm/versions/node/v10.16.3/lib/node_modules/balena-cli/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/Users/paulo/.nvm/versions/node/v10.16.3/lib/node_modules/balena-cli/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/paulo/.nvm/versions/node/v10.16.3/lib/node_modules/balena-cli/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/paulo/.nvm/versions/node/v10.16.3/lib/node_modules/balena-cli/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/paulo/.nvm/versions/node/v10.16.3/lib/node_modules/balena-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
```

In the case of the UI, the pop-up dialog reads "An error occurred while updating some devices", while the Chrome network inspect showed a 500 Internal Server Error request (sadly I accidentally closed the tab before copy-and-paste of headers and payloads).

**This seems to occur after a host OS update is attempted and fails. A workaround / fix is to reboot the device.**

The devices were Odroid XU4 running balenaOS 2.38.3+rev2 production, supervisor 9.15.7.

There may not be enough information above to act on it, but in this case this issue could be a placeholder for more information to be added later.

See: https://www.flowdock.com/app/rulemotion/resin-frontend/threads/MDWdk6sVFplzPilMTDSUv_g4zVy

**Comment by imrehg** [comment]
Tried to reproduce and cannot.
It seems temporary backend issues (IMHO VPN related issue strikes, that the script wasn't possible to get on the device)
